redis_queue:
  connection: 
    connection_url: "redis_test_url"

  ### For Inbound ###
  inbound:
    acapy_inbound_topic: "acapy-inbound-message"
    acapy_direct_resp_topic: "acapy-inbound-direct-resp"

  ### For Outbound ###
  outbound:
    acapy_outbound_topic: "acapy-outbound-message"
    acapy_outbound_retry_topic: "acapy-outbound-retry"

  ### For Event ###
  event:
    topic_maps:
      ^acapy::webhook::(.*)$: acapy-webhook-$wallet_id
      ^acapy::record::([^:]*)::([^:]*)$: acapy-record-with-state-$wallet_id
      ^acapy::record::([^:])?: acapy-record-$wallet_id
      acapy::basicmessage::.*: acapy-basicmessage