version: "3" 
services:
  deliverer:
    environment:
      - REDIS_SERVER=${REDIS_SERVER}
      - TOPIC_PREFIX=${TOPIC_PREFIX}
      - STATUS_ENDPOINT_TRANSPORT=${STATUS_ENDPOINT_TRANSPORT}
      - STATUS_ENDPOINT_API_KEY=${STATUS_ENDPOINT_API_KEY}
    networks:
      - delivey_service_network
    ports:
      - ${STATUS_ENDPOINT_PORT}:${STATUS_ENDPOINT_PORT}
    build: 
      context: ..
      dockerfile: ./deliverer/Dockerfile
networks:
  delivey_service_network:
    external: true
    name: ${NETWORK_NAME}